### ISSUE TITLE
how to set host

### ISSUE THREAD

**Issue by RonanCN** [alpeware/chrome-headless-trunk#10]
I had deployed this image in k8s .  and use ingress to config a hostname like ( chrome.k3s.onedayapp.cn ).

And it is not correct in the browser.

```
Host header is specified and is not an IP address or localhost.
```

How can i definition the hostname in k8s or docker ?

**Comment by alpeware** [comment]
I'm not sure where the error message is from, but you can specify the `--hostname` flag when starting your container in Docker [0].

Also, I briefly visited the URL you posted and it seems its accessible without a login. You might want to add some authentication.

Hope this helps and I'm going to close this issue.

[0] https://docs.docker.com/config/containers/container-networking/#ip-address-and-hostname
