### ISSUE TITLE
image does not respect "docker stop"

### ISSUE THREAD

**Issue by neelance** [alpeware/chrome-headless-trunk#2]
I can't terminate the container via "docker stop", only "docker kill" works. We're using this image on our CI system and this gives trouble.

**Comment by alpeware** [comment]
Thanks for using the image and apologies for the late reply.

Are you still experiencing issues in your CI environment?

I'm unable to reproduce this on my machine and `docker stop` seems to work fine for both interactive and daemon mode of the image.

I'm certainly no bash expert either, so happy to make changes to help make the image more useful for you guys.

Here's my docker info -

```
$ docker info
Containers: 93            
 Running: 3                          
 Paused: 0        
 Stopped: 90  
Images: 357          
Server Version: 17.06.0-ce       
Storage Driver: overlay                                                                                          
 Backing Filesystem: extfs                                                
 Supports d_type: true                                                    
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:          
 Volume: local               
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active       
 NodeID: q7r1nmlj5hemsjr3vqvwbo6u8
 Is Manager: true         
 ClusterID: w2y1k3gwg1i9dtlc1hsgs0k6e
 Managers: 1                                                   
 Nodes: 1                       
 Orchestration:           
  Task History Retention Limit: 5
 Raft:                                                                                                           
  Snapshot Interval: 10000                                                
  Number of Old Snapshots to Retain: 0                                    
  Heartbeat Tick: 1 
  Election Tick: 3
 Dispatcher:               
  Heartbeat Period: 5 seconds
 CA Configuration:
 Expiry Duration: 3 months
  Force Rotate: 0   
 Root Rotation In Progress: false
 Node Address: 192.168.1.9
 Manager Addresses:
  192.168.1.9:2377                                             
Runtimes: runc                  
Default Runtime: runc     
Init Binary: docker-init  
containerd version: d24f39e203aa6be4944f06dd0fe38a618a36c764 (expected: cfb82a876ecc11b5ca0977d1733adbe58599088a)
runc version: 2d41c04 (expected: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4)
init version: v0.15.0 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:   
 seccomp    
  Profile: default         
Kernel Version: 4.4.39-gentoo
Operating System: Gentoo/Linux                                                           
OSType: linux                                    
Architecture: x86_64
CPUs: 4
Total Memory: 15.56GiB
Name: tinybeast
ID: HWAU:7ADI:TLGN:CNV6:5LZ5:V4UG:KTX7:377K:WE2B:64YE:DA4D:XWFT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: simonpure
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by neelance** [comment]
Here is what I'm doing: I'm running the command from your README:
```
docker run -it --rm -p=0.0.0.0:9222:9222 --name=chrome-headless -v /tmp/chromedata/:/data alpeware/chrome-headless-trunk
```

I'm then running this in another terminal:
```
docker stop chrome-headless
```

This takes 10 seconds to complete, because the default timeout before the container is terminated forcefully (SIGKILL) is 10 seconds:

```
> docker stop --help

Usage:	docker stop [OPTIONS] CONTAINER [CONTAINER...]

Stop one or more running containers

Options:
      --help       Print usage
  -t, --time int   Seconds to wait for stop before killing it (default 10)
```

So if I instead do
```
docker stop chrome-headless -t 60
```
then it takes a full minute until the container gets terminated. On our CI that timeout is even higher for some other reason.

This means the container is not responding to the "please shut down now" signal (SIGTERM) that gets sent first.

**Comment by alpeware** [comment]
Thanks for the clarification. Should have looked at the exit code.

Your proposed fix doesn't seem to work for me. However, it seems I can extend the startup script to trap SIGTERM and then kill the chrome process as described here: https://goo.gl/MuYxqu

Should have this out shortly.

**Comment by alpeware** [comment]
It's currently building the image with the latest tag on Docker Hub.

Appreciate if you could let me know if this fixes the issue on your end as well.

Thanks!

**Comment by neelance** [comment]
`docker stop` now works for me, thanks for fixing that issue. I wonder why my solution did not work, it did the trick on another docker image. One downside of your approach is that it is less clean, it only fixes exactly my issue. For example sending other signals to the docker container will still not work.

**Comment by alpeware** [comment]
I agree and not sure why this didn't work for me. I'll see if I find some
more time to dig into it. Did your fix work for you locally?

Also, are there any other signals you depend on we can add in the meantime
to help run things smoothly in your CI environment?

**Comment by alpeware** [comment]
I added ```dumb-init [0]``` instead, so all signals should come through properly.

Let me know if you noticed any other issues or regressions!

[0] https://github.com/Yelp/dumb-init

**Comment by neelance** [comment]
I just tested the new version on our CI system. It works fine. Thanks!
