### ISSUE TITLE
Static browser endpoints?

### ISSUE THREAD

**Issue by icarusmiles** [alpeware/chrome-headless-trunk#4]
Is there anyway to make a default/static browser WS Endpoint?

Currently it starts with this: `ws://0.0.0.0:9222/devtools/page/667b57ee-15eb-4c84-be4c-a6cf6ada2546`
Anyway to make it always spawn like this: `ws://0.0.0.0:9222/browser` or connect to it like that.

**Comment by ali-habibzadeh** [comment]
Please reopen this issue. It not possible at all to use this with a load balancer as there is no way to get hold of browser ids or page ids from an outside context.

**Comment by ali-habibzadeh** [comment]
> Is there anyway to make a default/static browser WS Endpoint?
> 
> Currently it starts with this: `ws://0.0.0.0:9222/devtools/page/667b57ee-15eb-4c84-be4c-a6cf6ada2546`
> Anyway to make it always spawn like this: `ws://0.0.0.0:9222/browser` or connect to it like that.

@icarusmiles, Did you ever find a solution to this? Please reopen this issue. It not possible at all to use this with a load balancer as there is no way to get hold of browser ids or page ids from an outside context.

**Comment by ali-habibzadeh** [comment]
For anyone who ended up here because they couldn't make this work with AWS ALB, don't pull this, pull browserless/chrome:latest which will give you a consistent url on 3000
