### ISSUE TITLE
pull docker in macbook

### ISSUE THREAD

**Issue by curtis-go** [alpeware/chrome-headless-trunk#5]
{"error":{"code":-32601,"message":"'Page.navigate' wasn't found"},"id":1}

but getVersion:
{"id":1,"result":{"protocolVersion":"1.2","product":"HeadlessChrome/66.0.3335.0","revision":"@b7a0a6175bc4689719425d08e980713c80d302d2","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/66.0.3335.0 Safari/537.36","jsVersion":"6.6.100"}}

**Comment by alpeware** [comment]
@jixianlqb were you able to resolve this issue?

I'm not familiar with this particular error, but from quickly googling it [0], it might be related to the client you are using to connect to the headless instance.

Feel free to share additional details here so we can document for anyone else having similar issues.

Thanks!

[0] https://www.reddit.com/r/webdev/comments/7dlsk4/headless_chrome_asaservice_includes_docker_images/

**Comment by alpeware** [comment]
I'm going to close out this issue.

Feel free to open a new one with additional details if you're still having issues!
