### ISSUE TITLE
Upgrade Ubuntu due to 14.04 LT transitioning to ESM

### ISSUE THREAD

**Issue by gidztech** [alpeware/chrome-headless-trunk#8]
Ubuntu 14.04 LT has transitioned to ESM because it's end-of-life: https://ubuntu.com/blog/ubuntu-14-04-esm-support
It's not possible to fetch packages from the repository without UA Infrastructure Essential credentials.

The version of Ubuntu should be upgraded, presumably to the latest? I don't know what the consequences of this would be other than fixing the authentication issues currently faced.

**Comment by alpeware** [comment]
Yeah good point @gidztech and thanks for pointing this out. I've upgraded the base image to 18.04.
