### ISSUE TITLE
Docker images stopped publishing

### ISSUE THREAD

**Issue by noahw3** [alpeware/chrome-headless-trunk#9]
It looks like on January 29 the automatic docker publishes started failing.

The last image published was rev-736695.

https://hub.docker.com/r/alpeware/chrome-headless-trunk/tags
https://github.com/alpeware/chrome-headless-trunk/commits/master?before=7064fda45c523792c949eda5f9f222c343fc51a5+2966

**Comment by alpeware** [comment]
Finally had some time to look into this. The Docker Hub UI is not very helpful. Anyway, it should be building again.

Thanks @noahw3 for letting me know!
